{% set name = "xarray-datatree" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-datatree-{{ version }}.tar.gz
  sha256: 26169af35b0df0d17652e229cef210decf0711dd88e33419142edc6674113af4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
  run:
    - python >=3.8
    - xarray >=2022.6

test:
  imports:
    - datatree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/datatree
  summary: Hierarchical tree-like data structures for xarray
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://xarray-datatree.readthedocs.io/en/latest
  dev_url: https://github.com/xarray-contrib/datatree


extra:
  recipe-maintainers:
    - andersy005
    - TomNicholas
