{% set name = "xarray-datatree" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-datatree-{{ version }}.tar.gz
  sha256: 8c93687e765dbbfaae01d1cf3dafae2a6f22f7b90e34bc0989cb425710a1a684

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
  run:
    - python >=3.8
    - xarray >=0.20.2

test:
  imports:
    - datatree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/datatree
  summary: Hierarchical tree-like data structures for xarray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
