{% set name = "xarray-datatree" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-datatree-{{ version }}.tar.gz
  sha256: 21b05d2887b305c78411871328437e5cccd41ee07d16bda024b758e72e39554b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
  run:
    - anytree >=2.8.0
    - python >=3.8
    - xarray >=0.20.2

test:
  imports:
    - datatree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/datatree
  summary: Hierarchical tree-like data structures for xarray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
