{% set name = "xarray-datatree" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4e828086d858742e4dec7ed7e9187865d5215302919d0e02a613dce0ff0db003

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
  run:
    - python >=3.8
    - xarray >=2022.6

test:
  imports:
    - datatree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/datatree
  summary: Hierarchical tree-like data structures for xarray
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://xarray-datatree.readthedocs.io/en/latest
  dev_url: https://github.com/xarray-contrib/datatree


extra:
  recipe-maintainers:
    - andersy005
    - TomNicholas
